// global
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_WINDOWHEIGHT = 'SET_WINDOWHEIGHT'
export const SET_WINDOWWIDTH = 'SET_WINDOWWIDTH'
export const SET_BREADCRUMB = 'SET_BREADCRUMB'
export const SET_PAGE_BREADCRUMB = 'SET_PAGE_BREADCRUMB'
// application
export const SET_APPLICATION_PAGE = 'SET_APPLICATION_PAGE'
export const SET_APPLICATION_SEARCH_QUERY = 'SET_APPLICATION_SEARCH_QUERY'

// 申请审核 examine
export const SET_EXAMINE_TABLEDATA = 'SET_EXAMINE_TABLEDATA'
export const SET_EXAMINE_DETAIL = 'SET_EXAMINE_DETAIL'
export const SET_EXAMINE_SEARCH_QUERY = 'SET_EXAMINE_SEARCH_QUERY'
export const SET_EXAMINE_BACKPATH = 'SET_EXAMINE_BACKPATH'

// 角色管理
export const SET_ROLEMANAGE_PAGE = 'SET_ROLEMANAGE_PAGE'
export const PERSON_PAGE = 'PERSON_PAGE'
export const LIST_ID = 'LIST_ID'
export const ROLE_ID = 'ROLE_ID'
