// global
export const SET_WINDOWHEIGHT = 'SET_WINDOWHEIGHT'
export const SET_WINDOWWIDTH = 'SET_WINDOWWIDTH'
export const SET_BREADCRUMB = 'SET_BREADCRUMB'
export const SET_PAGE_BREADCRUMB = 'SET_PAGE_BREADCRUMB'
export const GET_CONFIRM_INFO = 'GET_CONFIRM_INFO'
// application
export const SET_APPLICATION_PAGE = 'SET_APPLICATION_PAGE'
export const SET_APPLICATION_SEARCH_QUERY = 'SET_APPLICATION_SEARCH_QUERY'

// 申请审核 examine
export const SET_EXAMINE_TABLEDATA = 'SET_EXAMINE_TABLEDATA'
export const SET_EXAMINE_DETAIL = 'SET_EXAMINE_DETAIL'
export const SET_EXAMINE_SEARCH_QUERY = 'SET_EXAMINE_SEARCH_QUERY'
export const SET_EXAMINE_BACKPATH = 'SET_EXAMINE_BACKPATH'

// 角色管理
export const SET_ROLEMANAGE_PAGE = 'SET_ROLEMANAGE_PAGE'
export const PERSON_PAGE = 'PERSON_PAGE'
export const LIST_ID = 'LIST_ID'
export const ROLE_ID = 'ROLE_ID'

// 角色信息
export const SET_ROLE_INFO = 'SET_ROLE_INFO'
// 通知类型和通知方式
export const SET_NOTICE_WAY = 'SET_NOTICE_WAY'
export const SET_NOTICE_TYPE = 'SET_NOTICE_TYPE'

// 系统数据
export const SET_APPLY_LIST = 'SET_APPLY_LIST'
